[ports-mingw] emacs: Fix compiling with clang due to sys/wait.h
Compiling with clang failed due to wait(2) function is not declared in
emcas sys/wait.h file. The following error is shown in config.log file

conftest.c:70:3: error: call to undeclared function 'wait'; ISO C99 and
later do not support implicit function declarations [-Wimplicit-function-declaration]

This adds the suggestion from https://lists.gnu.org/archive/html/help-gnu-emacs/2023-05/msg00107.html

Source: msys2/MINGW-packages@176a94495685943980e3ff7c81b440c1ba0b27f9