[ports-mingw] libfilezilla: Update to 0.52.0
disable static build due to:
error: libfilezilla does not support --enable-static

Source: msys2/MINGW-packages@0190d1c89f2470d8f8b759fb552e01642f8f00b7