[ports-mingw] ffmpeg: rebuild and backport a build fix
Fixes:
error: incompatible function pointer types initializing 'PFN_vkDebugUtilsMessengerCallbackEXT'

for clang32 since clang v16

Source: msys2/MINGW-packages@e6d067697e88e5cd6058445c7f03b755ebbd2df5