[ports] mintty: update to 3.7.2
Use one job with make command to workaround the following error.

appinfo.c:2:10: fatal error: appinfo.t: No such file or directory
2 | #include "appinfo.t"
  |          ^~~~~~~~~~~

Source: msys2/MSYS2-packages@20f2ab1f0921f4c232e0fffe21e80b52da0abd04