[ports-mingw] fox: Enable fox for clangarm64; Update to version 1.6.59 (#22850)
* Enable fox for clangarm64

"-Wno-register" avoids lot of clang errors kind of:
  error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]

* fox: Update to version 1.6.59

Although the release notes mentions this, it doesn't fix the issue of using "register" keyword on clang.
So "-Wno-register" is still necessary.

Source: msys2/MINGW-packages@5e1d57e2d95b572a05c94c005bebcd42a5cb7d21