[ports-mingw] Disable clangarm64 for some packages which fail to build
mingw-w64-vapoursynth
    vscore.cpp:959:10: error: use of undeclared identifier 'vs_isSSEStateOk'

mingw-w64-uasm
    assemble.c:1181:3: error: call to undeclared function 'AddSimdTypes'

mingw-w64-tkimg
    ld.lld: error: undefined symbol: png_riffle_palette_neon

mingw-w64-texstudio
    debug/debughelper.cpp:370:10: error: no member named 'Eip' in '_CONTEXT'

mingw-w64-soil
    make: gcc: No such file or directory

mingw-w64-snoregrowl
    gntp-send.cpp:38:10: error: no member named 'auto_ptr' in namespace 'std'

mingw-w64-silc-toolkit
    silcwin32thread.c:69:29: error: incompatible function pointer types passing 'LPTHREAD_START_ROUTINE'

mingw-w64-ruby
    unexpected ucrtbase.dll

mingw-w64-quantlib
    boost/functional.hpp:45:24: error: no member named 'unary_function' in namespace 'std'; did you mean '__unary_function'

mingw-w64-python2
    posixmodule.c:1846:73: error: incompatible function pointer types passing

mingw-w64-python-pygame
    src_c/pypm.c:4767:81: error: incompatible function pointer types passing

mingw-w64-python-lief
    examples/c/pe_reader.c:107:15: error: redefinition of 'i'

mingw-w64-premake
    Error: no value specified for option 'arch'

mingw-w64-pqp
    src/OBB_Disjoint.h:64:3: error: ISO C++17 does not allow 'register' storage class specifier

mingw-w64-postgis
    ptarray.c:2196:2: error: call to undeclared library function 'bzero' with type

mingw-w64-pkg-config
    gatomic.c:392:10: error: incompatible integer to pointer conversion passing 'gssize'

mingw-w64-perl-win32-api
    call_asm_x64_gnu.s:5:8: error: unknown token in expression

mingw-w64-pelican
    TypeError: not all arguments converted during string formatting

mingw-w64-itk
    Cannot have VNL_CONFIG_ENABLE_SSE2_ROUNDING because there is no SSE2 hardware support

mingw-w64-newton-dynamics
    include/emmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"

mingw-w64-msmpi
    cannot open file C:/M/B/src/msmpi.def.aarch64: No such file or directory

mingw-w64-mecab
    src/darts.h:407:5: error: ISO C++17 does not allow 'register' storage class specifier

mingw-w64-mcpp
    Invalid configuration `aarch64-w64-mingw32': machine `aarch64-w64' not recognized

mingw-w64-mbedtls
    include/arm_neon.h:62829:32: error: always_inline function 'vget_high_p64' requires target feature 'crypto', but would be inlined into function 'vmull_high_p64' that is compiled without support for 'crypto'

mingw-w64-mathgl
    prc/writePRC.h:410:1: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'

mingw-w64-libxml++2.6
    warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"

mingw-w64-libxml++
    xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl

mingw-w64-libsigsegv
    src/handler-win32.c:219:45: error: no member named 'Rsp' in 'struct _CONTEXT'

mingw-w64-librasterlite2
    src/rl2jpeg.c:240:28: error: incompatible function pointer types assigning to

mingw-w64-libmowgli
    eventloop/eventloop.h:217:19: error: incompatible function pointer types assigning to 'ULONGLONG

mingw-w64-liblo
    src/test_bidirectional_tcp.c:79:26: error: call to undeclared function '_beginthreadex'

mingw-w64-libiptcdata
    Invalid configuration `aarch64-w64-mingw32': machine `aarch64-w64' not recognized

mingw-w64-libevent
    sample/http-server.c:559:9: error: incompatible function pointer types passing

mingw-w64-libconfig
    lib/libconfig.c:703:10: error: call to undeclared function 'fsync'

mingw-w64-libart_lgpl
    Invalid configuration `aarch64-w64-mingw32': machine `aarch64-w64' not recognized

mingw-w64-lib3mf
    zip_source_file_win32_utf16.c:45:5: error: incompatible function pointer types initializing

mingw-w64-leveldb
    internal/gtest-port.h:270:2: error: C++ versions less than C++14 are not supported.

mingw-w64-jom
    ppexpr-lex.inc:746:2: error: ISO C++17 does not allow 'register' storage class specifier

mingw-w64-helics
    ld.lld: error: undefined symbol: __cpuid

mingw-w64-global
    ld.lld: error: undefined symbol: __declspec(dllimport) initscr

mingw-w64-freerdp
    wtsapi/wtsapi_win32.c:805:31: error: incompatible function pointer types assigning to

mingw-w64-fox
    FXUTF8Codec.cpp:49:3: error: ISO C++17 does not allow 'register' storage class specifier

mingw-w64-ffcall
    avcall-arm64.s:6:8: error: expected absolute expression

mingw-w64-expresscpp
    middleware/serve_static_provider.cpp:107:17: error: implicit instantiation of undefined template 'std::basic_ifstream<char>'

mingw-w64-enca
    enca-1.19/src/options.c:247:27: error: incompatible integer to pointer conversion passing 'int' to parameter of type

mingw-w64-eccodes
    ld.lld: error: undefined symbol: jpc_decode

mingw-w64-dwarfstack
    src/dwst-exception.c:118:31: error: no member named 'Rip' in 'struct _CONTEXT'

mingw-w64-dust
    ld.lld: error: undefined symbol: RtlGetVersion

mingw-w64-db
    Invalid configuration `aarch64-w64-mingw32': machine `aarch64-w64' not recognized

mingw-w64-bmake
    bmake/compat.c:200:9: error: call to undeclared function 'killpg'

mingw-w64-avr-gdb
    gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 15] for this enumeration type

mingw-w64-arm-none-eabi-gdb
    common/nrun.c:219:4: error: call to undeclared function 'strsignal'

mingw-w64-alure
    alure-1.2/include/main.h:313:18: error: no template named 'auto_ptr' in namespace 'std'

mingw-w64-editorconfig-qtcreator
    Could not find a package configuration file provided by "QtCreator" with any of the following names

Source: msys2/MINGW-packages@55863e447a5b73bb20fe3c7d66ee217a686c7daf