[ports-mingw] python-xpra: add missing dependency on lz4
ERROR: call to 'pkg-config --libs liblz4' failed

Source: msys2/MINGW-packages@81cb1bf6fcdf8d8f14eb8dbace65222274e0f19f