[ports-mingw] Revert "Rust: disable mingw packaging via configuration option"
This reverts commit 706daae6b5b880201d00dae7d84909264d2f6cc9.

This results in a broken rust (or some other change since the last rebuild):

error: linking with `x86_64-w64-mingw32-clang` failed: exit code: 1
note: x86_64-w64-mingw32-clang: error: no such file or directory: 'crt2.o'

See https://github.com/msys2/MINGW-packages/pull/17777#issuecomment-1666132597

Source: msys2/MINGW-packages@1717c9e1f31701e6958bc1ad0cc3927cb07e20ec