[ports-mingw] Revert "Try to build nspr/nss for clangarm64"
This reverts commit cb8dfab77063d8c06a836c09f12fad252984840d.

nspr fails with:

nspr-4.34/nspr/pr/include/md/_winnt.h:42:2: error: unknown processor architecture

Source: msys2/MINGW-packages@f89df0da71e53273ca66a4548cd7752bb2de1c05