[ports-mingw] osgearth: update to 3.5
disable on mingw64, fails to link `undefined reference to `__imp__dupenv_s'`
`_dupenv_s' doesn't exist in msvcrt runtime

Source: msys2/MINGW-packages@0b6aefea8793750d40e90e0175054952f9cf8558