Now the devel-deps handled properly
bootstrap

update package version

fixes bootstrap.sh

Install gcc properly

xx

libtool

libtool libltdl

gpg --recv-keys

Now we can building every packages.

gen-build-all.mjs

bootstrap is building

deps.json

db is now the start point

bootstraping

Now bootstrap can working fine

Try building gcc first

bootstrap gcc properly

ports

Now gcc can be built properly.

Change to depends on cyg

update bootstrap-extras.sh

gmp building fine

running bootstrap

msys2-runtime shrink.

sh bootstrap-extras.sh

bootstrap.sh

3.6.5.5 is not building gcc

msys2-runtime-devel-3.6.5.6-1-x86_64.pkg.tar.zst

install old version

new ports

/tmp

Try to build with original

bootstrap ..

libiconv twice

bootstrap

dist-init

make libtool depends cygwin

libtool for safety, depends the old msys-runtime

cmake and libtool are fine now

what's wrong

bootstrap-msys2-runtime.sh

building the reset

gcc msys2 runtime-3.6.5-5

bootstrap-gcc-stage0.sh

bootstrap things

bootstrap in clear way.

add build-all.sh

ncurses needs to built

groff depends on C++

gcc libstdc++ compiled

building start filesystem

groff failed with:

  CXX      src/libs/libgroff/libgroff_a-curtime.o
  CXX      src/libs/libgroff/libgroff_a-device.o
  CXX      src/libs/libgroff/libgroff_a-errarg.o
  CXX      src/libs/libgroff/libgroff_a-error.o
  CXX      src/libs/libgroff/libgroff_a-fatal.o
  CXX      src/libs/libgroff/libgroff_a-filename.o
  CXX      src/libs/libgroff/libgroff_a-font.o
  CXX      src/libs/libgroff/libgroff_a-fontfile.o
  CXX      src/libs/libgroff/libgroff_a-geometry.o
  CC       src/libs/libgroff/libgroff_a-getopt.o
src/libs/libgroff/getopt.c:125:14: error: conflicting types for ‘getenv’; have ‘char *(void)’
  125 | extern char *getenv ();
      |              ^~~~~~
In file included from ./lib/stdlib.h:36,
                 from ./src/include/getopt.h:34,
                 from src/libs/libgroff/getopt.c:77:
/usr/include/stdlib.h:95:9: note: previous declaration of ‘getenv’ with type ‘char *(const char *)’
   95 | char *  getenv (const char *__string);
      |         ^~~~~~
src/libs/libgroff/getopt.c: In function ‘_getopt_initialize’:
src/libs/libgroff/getopt.c:264:47: error: too many arguments to function ‘getenv’; expected 0, have 1
  264 |   d->__posixly_correct = posixly_correct || !!getenv ("POSIXLY_CORRECT");
      |                                               ^~~~~~  ~~~~~~~~~~~~~~~~~
src/libs/libgroff/getopt.c:125:14: note: declared here
  125 | extern char *getenv ();
      |              ^~~~~~
make[1]: *** [Makefile:7885: src/libs/libgroff/libgroff_a-getopt.o] Error 1
make[1]: Leaving directory '/c/work/xemu/CYGWIN-packages/ports/groff/src/groff-1.23.0'
make: *** [Makefile:6167: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error for pkgbase: groff with retcode:4

gzip building failed

  CC       libgzip_a-cloexec.o
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/sys/errno.h:11,
                 from /usr/include/errno.h:9,
                 from openat-priv.h:23,
                 from openat-proc.c:22:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
  CC       libgzip_a-crc.o
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/string.h:11,
                 from ./string.h:41,
                 from basename-lgpl.c:24:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
  CC       libgzip_a-crc-x86_64-pclmul.o
  CC       libgzip_a-dirname-lgpl.o
  CC       libgzip_a-stripslash.o
In file included from /usr/include/sys/types.h:45,
                 from ./sys/types.h:46,
                 from /usr/include/sys/unistd.h:12,
                 from /usr/include/unistd.h:4,
                 from ./unistd.h:40,
                 from chdir-long.h:19,
                 from chdir-long.c:21:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'; did you mean 'u_int8_t'?
  167 |     wint_t __wch;
      |     ^~~~~~
      |     u_int8_t
make[3]: *** [Makefile:2492: libgzip_a-basename-lgpl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/sys/errno.h:11,
                 from /usr/include/errno.h:9,
                 from cloexec.c:24:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
make[3]: *** [Makefile:2478: libgzip_a-openat-proc.o] Error 1
  CC       libgzip_a-endian.o
  CC       libgzip_a-exitfail.o
In file included from /usr/include/machine/endian.h:5,
                 from /usr/include/endian.h:13,
                 from ./endian.h:31,
                 from endian.h:31,
                 from crc.c:22:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'; did you mean 'uint8_t'?
  167 |     wint_t __wch;
      |     ^~~~~~
      |     uint8_t
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/stdlib.h:18,
                 from ./stdlib.h:51,
                 from dirname.h:28,
                 from dirname-lgpl.c:21:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
  CC       libgzip_a-fclose.o
make[3]: *** [Makefile:2618: libgzip_a-dirname-lgpl.o] Error 1
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/stdlib.h:18,
                 from ./stdlib.h:51,
                 from dirname.h:28,
                 from stripslash.c:21:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
make[3]: *** [Makefile:2576: libgzip_a-crc.o] Error 1
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/string.h:11,
                 from ./string.h:41,
                 from crc-x86_64-pclmul.c:24:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'; did you mean 'uint8_t'?
  167 |     wint_t __wch;
      |     ^~~~~~
      |     uint8_t
In file included from /usr/include/machine/endian.h:5,
                 from /usr/include/endian.h:13,
                 from ./endian.h:31,
                 from endian.c:23:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/stdio.h:60,
                 from ./stdio.h:55,
                 from fclose.c:20:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/stdlib.h:18,
                 from ./stdlib.h:51,
                 from exitfail.c:22:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
make[3]: *** [Makefile:2534: libgzip_a-cloexec.o] Error 1
make[3]: *** [Makefile:2632: libgzip_a-stripslash.o] Error 1
make[3]: *** [Makefile:2674: libgzip_a-endian.o] Error 1
make[3]: *** [Makefile:2702: libgzip_a-exitfail.o] Error 1
make[3]: *** [Makefile:2520: libgzip_a-chdir-long.o] Error 1
make[3]: *** [Makefile:2730: libgzip_a-fclose.o] Error 1
make[3]: *** [Makefile:2590: libgzip_a-crc-x86_64-pclmul.o] Error 1
make[3]: Leaving directory '/c/work/xemu/CYGWIN-packages/ports/gzip/src/gzip-1.14/lib'
make[2]: *** [Makefile:2266: all] Error 2
make[2]: Leaving directory '/c/work/xemu/CYGWIN-packages/ports/gzip/src/gzip-1.14/lib'
make[1]: *** [Makefile:2110: all-recursive] Error 1
make[1]: Leaving directory '/c/work/xemu/CYGWIN-packages/ports/gzip/src/gzip-1.14'
make: *** [Makefile:1891: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error for pkgbase: gzip with retcode:4

mpc depends on mpfr

libargp build failed with gcc 15

o -MD -MP -MF $depbase.Tpo -c -o glthread/lock.lo ../../argp/gllib/glthread/lock.c &&\
mv -f $depbase.Tpo $depbase.Plo
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/stdlib.h:18,
                 from ./stdlib.h:51,
                 from ../../argp/gllib/argp-fmtstream.c:26:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~

libbobcat

libunistring failed with:

    exit 1; \
  fi \
fi
gcc -DHAVE_CONFIG_H -DNO_XMALLOC -I. -I..  -I. -I. -I.. -I.. -DIN_LIBUNISTRING -DDEPENDS_ON_LIBICONV=1   -march=nocona -msahf -mtune=generic -O2 -pipe -c amemxfrm.c
In file included from /usr/include/sys/reent.h:16,
                 from /usr/include/sys/errno.h:11,
                 from /usr/include/errno.h:9,
                 from amemxfrm.c:23:
/usr/include/sys/_types.h:167:5: error: unknown type name 'wint_t'
  167 |     wint_t __wch;
      |     ^~~~~~
make[2]: *** [Makefile:10109: config.h] Error 1
make[2]: Leaving directory '/c/work/xemu/CYGWIN-packages/ports/libunistring/src/libunistring-1.3/lib'
make[1]: *** [Makefile:2439: all-recursive] Error 1
make[1]: Leaving directory '/c/work/xemu/CYGWIN-packages/ports/libunistring/src/libunistring-1.3'
make: *** [Makefile:2367: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error for pkgbase: libunistring with retcode:4

m4 has error:

make[3]: *** Waiting for unfinished jobs....
  CC       closeout.o
  CC       concat-filename.o
In file included from ../../m4-1.4.19/lib/clean-temp-private.h:22,
                 from ../../m4-1.4.19/lib/clean-temp-simple.c:22:
../../m4-1.4.19/lib/gl_list.h:633:1: warning: 'nodiscard' attribute ignored [-Wattributes]
  633 | GL_LIST_INLINE _GL_ATTRIBUTE_NODISCARD int
      | ^~~~~~~~~~~~~~
../../m4-1.4.19/lib/gl_list.h:633:40: error: expected identifier or '(' before 'int'
  633 | GL_LIST_INLINE _GL_ATTRIBUTE_NODISCARD int
      |                                        ^~~

Now building start with pax

building start with sgml-common

tzcode fixed

yodl: Remove bool enum that conflict with c23

apr: Fixes building

cscope

rename to extract

update bootstrap-extract.sh

prepare to building icu

msys2-runtime 3.6.5-7

MSYS_BOOTSTRAP_STAGE

gcc fixes building

gnupg building fine

Change the list

getting cmake to be built

rest

help2man are building properly

Clean dll and exe:

autogen should not be part of base-devel

perl-YAML-Syck are also built as dll.

cleanup dlls properly

Do not building perl module that comes with dll

Revise build script

Fixes building of more packages.

MSYS_BUILD_BASE_DEVEL=enabled sh build-single.sh gcc working

Try to building stage1 gcc properly

Now gcc is built

Building gcc properly in build-base-devel.sh

Moved more package into build-base-devel.sh

python depends on  libgdbm-devel libutil-linux-devel

sqlite should not depends on icu-devel

Do not build cmake-bootstrap

Add python.sh

building them fine

Now split build-all.sh out

prepare to filter extra out.

meson also need to be built

perl depends on libbsd

Now for tcl, install all files.

Add build-single.sh

the ./tmp also need to be coped.

Smaller build-all.sh

gnupg also need to be built

Now bootstraping base-devel

gnupg are building

try building glib2 properly

python installed

Now bash perl coreutils gawk are working