[ports-mingw] gst-plugins-base: don't try to build with gles2/egl support
So we have a reproducibel build. Also the egl backend doesn't build:

gst-libs/gst/gl/egl/gstglcontext_egl.c:773:7: error: too few arguments to function 'gst_gl_window_win32_create_window'

Source: msys2/MINGW-packages@4b72fae61cb6357ef83ccc32f4e9f274fbc47188