[ports-mingw] abseil-cpp: Workaround compiler error due to absence of ICalendar definition
This fixes the following compiler error.
time_zone_lookup.cc:102:14: error: use of undeclared identifier 'RuntimeClass_Windows_Globalization_Calendar'

Source: msys2/MINGW-packages@57879db05e8f9382125d432b61fac2248bc5e35b