[ports-mingw] Revert "lsd: update to 1.1.2"
This reverts commit 6cd29d169a6246b0af1af29e7dcaaf70f1a1f409.

Failed with:
error: the lock file C:\M\B\src\lsd-1.1.2\Cargo.lock needs to be updated but --locked was passed to prevent this

Source: msys2/MINGW-packages@fa7ce02554aaa1f4f0f7cf7401fd751972090572