[ports-mingw] bison: it builds.
ERROR: 407 tests were run,
247 failed unexpectedly.
30 tests were skipped.

.. I checked the first failure and
it was down newline differences e.g.:

"Error: blah\r\n" not matching "Error: blah\n"

This needs to be fixed in Autotest (part of Autoconf),
something like this libtool patch:

https://www.mail-archive.com/libtool-patches@gnu.org/msg04437.html

Source: msys2/MINGW-packages@f874cdb2b28ee530f25b293371e81be750ed5d57