[ports-mingw] sqlite3: update to 3.43.0
The new patch file fixes the following compiler error.

../../../sqlite-src-3430000/ext/misc/pcachetrace.c:29:8: error: unknown type name 'sqlite3_pcache_methods2'
   29 | static sqlite3_pcache_methods2 pcacheBase;
      |        ^~~~~~~~~~~~~~~~~~~~~~~

Source: msys2/MINGW-packages@cdfe2676ac9ef8df50562ccdb3eab40cffed3881