[ports-mingw] libid3tag: fix build
- add 006-libid3tag-0.15.1b-gperf-size_t.patch
  Fixes the following error:
  frametype.gperf:322:1: error: conflicting types for
  'id3_frametype_lookup'
  In file included from frametype.gperf:32:
  ../libid3tag-0.15.1b/frametype.h:39:29: note: previous declaration
  of 'id3_frametype_lookup' was here
     39 | struct id3_frametype const *id3_frametype_lookup(register
- remove compat.c and frametype.c from the source dir, so that they are
  regenerated from the .gperf sources during build. The files compat.c
  and frametype.c in the tarball have been produced using gperf 3.0.1,
  whereas in the meantime gperf is at version 3.1
- Fix version in id3tag.pc

Source: msys2/MINGW-packages@909d90f61d73e6073d4b8ac80753b5ad631b0340