[ports-mingw] podofo: update to 0.9.7
- Update fix-export.patch
- Remove remove-broken-command.patch
  Not needed anymore, fixed upstream:
  https://sourceforge.net/p/podofo/code/1942/
- Add patch: 003-podofo-0.9.7-localtime_r.patch
  Fixes:
    src/podofo-0.9.7/test/unit/DateTest.cpp:143:5: error: 'localtime_r'
    was not declared in this scope; did you mean 'localtime_s'?

Source: msys2/MINGW-packages@b99c4868f8aa5e18588db297ddd4e4654dd1974e