[ports-mingw] volk: Fix running volk_modtool python script
This fixes the following runtime error.
ImportError: cannot import name 'volk_modtool' from partially initialized module 'volk_modtool' (most likely due to a circular import)

Source: msys2/MINGW-packages@a06e49e2fba823c5ab658583e81285aff9d9f8f0