[ports] msys2-runtime: set -Wno-error=maybe-uninitialized
After the update of msys2-w32api from v11.0.1 to current master (and
soon to be v12) we get: winsup/cygwin/exceptions.cc:1736:33: error:
'<anonymous>' may be used uninitialized [-Werror=maybe-uninitialized]

Ignore it like the rest.

Fixes msys2/msys2-runtime#214

Source: msys2/MSYS2-packages@374a194eb9f0642112d67199dd326170501a6ca7