[ports] gradle: Package missing files (#6255)
Fixes:

    org.gradle.api.internal.classpath.UnknownModuleException: Cannot find module 'ant' in distribution directory 'C:\msys64\usr\share\java\gradle'.

Source: msys2/MSYS2-packages@e986246feac67689b8f9345c72ab75afb6332fa3