[ports] aspell: fix PKGBUILD
function CHECK:
- fix variable
- remove make flag '-k'
- remove .sig file from sources since public key unknown
  ERROR: aspell-0.60.8.tar.gz ... FAILED (unknown public key B6D9D0CC38B327D7)

Source: msys2/MSYS2-packages@a95a8d1ffc8a875e5ae29a490968330c105b5646