[ports-mingw] qt6-static: turn on system harfbuzz
It's already being pulled in via freetype, apparently, because I get

 ld.lld: error: duplicate symbol: hb_font_funcs_create
 >>> defined at libQt6BundledHarfbuzz.a(hb-font.cc.obj)
 >>> defined at libharfbuzz.a(hb-font.cc.obj)

Source: msys2/MINGW-packages@c5cde844853e028d533839ad2585597a2f1ed20f