[ports-mingw] mesa: Fix building AMD vulkan driver
_tzcnt_u32 requires Skylake or newer CPU[1]. So, it fails to build in
msys2/mingw environment because the default target is older nocona.
The attached patch allows to check __builtin_ctz first. This reverts
the logic from 5bb1fc80fa2c91a6204d89c59b7288e941f94481 commit.

This fixes the following compiler error

bmiintrin.h: In function 'unsigned int Addr::BitScanForward(unsigned int)':
bmiintrin.h:116:1: error: inlining failed in call to 'always_inline' 'unsigned int _tzcnt_u32(unsigned int)':
 target specific option mismatch
  116 | _tzcnt_u32 (unsigned int __X)
      | ^~~~~~~~~~
../../src/amd/addrlib/src/core/addrcommon.h:360:23: note: called from here
  360 |     out = ::_tzcnt_u32(mask);
      |           ~~~~~~~~~~~~^~~~~~

[1]: https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_tzcnt_u32

Source: msys2/MINGW-packages@f13be94476d7ff5aeaa0fa7b34a6b03c1eb65bde